"""sync progress

Revision ID: ac67b173c6ab
Revises: e27e970f7788
Create Date: 2026-10-07 11:25:31.917129

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac67b173c6ab"
down_revision: str | Sequence[str] | None = "e27e970f7788"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sync_state", sa.String(length=16), server_default="idle", nullable=False)
        )
        batch_op.add_column(sa.Column("sync_message", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("sync_done", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("sync_total", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("sync_updated_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("sync_updated_at")
        batch_op.drop_column("sync_total")
        batch_op.drop_column("sync_done")
        batch_op.drop_column("sync_message")
        batch_op.drop_column("sync_state")

    # ### end Alembic commands ###
