"""initial schema

Revision ID: e27e970f7788
Revises:
Create Date: 2026-10-07 10:07:23.156014

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e27e970f7788"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strava_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("measurement", sa.String(length=10), nullable=False),
        sa.Column("access_token", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.Column("token_expires_at", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("ftp_watts", sa.Float(), nullable=True),
        sa.Column("run_threshold_speed", sa.Float(), nullable=True),
        sa.Column("css_speed", sa.Float(), nullable=True),
        sa.Column("lthr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("rest_hr", sa.Float(), nullable=True),
        sa.Column("race_name", sa.String(length=120), nullable=True),
        sa.Column("race_date", sa.Date(), nullable=True),
        sa.Column("race_climb_m", sa.Float(), nullable=False),
        sa.Column("race_wetsuit", sa.Boolean(), nullable=False),
        sa.Column("race_temp_c", sa.Float(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("strava_id"),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sport", sa.String(length=16), nullable=False),
        sa.Column("sport_type", sa.String(length=40), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("trainer", sa.Boolean(), nullable=False),
        sa.Column("moving_s", sa.Float(), nullable=False),
        sa.Column("elapsed_s", sa.Float(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("elev_gain_m", sa.Float(), nullable=False),
        sa.Column("avg_speed", sa.Float(), nullable=True),
        sa.Column("graded_speed", sa.Float(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("avg_watts", sa.Float(), nullable=True),
        sa.Column("np_watts", sa.Float(), nullable=True),
        sa.Column("device_watts", sa.Boolean(), nullable=False),
        sa.Column("relative_effort", sa.Float(), nullable=True),
        sa.Column("tss", sa.Float(), nullable=False),
        sa.Column("tss_method", sa.String(length=16), nullable=False),
        sa.Column("intensity", sa.Float(), nullable=True),
        sa.Column("ef", sa.Float(), nullable=True),
        sa.Column("decoupling_pct", sa.Float(), nullable=True),
        sa.Column("power_curve", sa.JSON(), nullable=True),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("has_streams", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "source", "external_id"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activities_athlete_id"), ["athlete_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_day"), ["day"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_sport"), ["sport"], unique=False)

    op.create_table(
        "wellness_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("sleep_s", sa.Float(), nullable=True),
        sa.Column("sleep_score", sa.Float(), nullable=True),
        sa.Column("hrv_ms", sa.Float(), nullable=True),
        sa.Column("rest_hr", sa.Float(), nullable=True),
        sa.Column("body_battery_high", sa.Float(), nullable=True),
        sa.Column("body_battery_low", sa.Float(), nullable=True),
        sa.Column("stress_avg", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["athlete_id"], ["athletes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "day"),
    )
    with op.batch_alter_table("wellness_days", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wellness_days_athlete_id"), ["athlete_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wellness_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wellness_days_athlete_id"))

    op.drop_table("wellness_days")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_sport"))
        batch_op.drop_index(batch_op.f("ix_activities_day"))
        batch_op.drop_index(batch_op.f("ix_activities_athlete_id"))

    op.drop_table("activities")
    op.drop_table("athletes")
    # ### end Alembic commands ###
